export const LoremIpsumLongText = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget posuere leo. Donec scelerisque lacinia commodo. Curabitur quis laoreet arcu. Fusce varius, turpis eget faucibus volutpat, risus mi aliquam magna, id vulputate turpis justo ac lorem. Proin vitae feugiat massa. Sed sit amet turpis vitae lorem sagittis tincidunt vel ac lacus. Nullam et purus orci. Donec semper dignissim justo non suscipit. Sed tempor neque id leo auctor, eget gravida enim imperdiet. Nulla vitae velit sed est suscipit ullamcorper. Vestibulum convallis euismod condimentum. Aliquam at felis gravida nulla accumsan lacinia et sit amet erat. Suspendisse in erat tincidunt, hendrerit nisl vel, viverra turpis. Nulla elementum arcu et nibh vulputate cursus. Mauris eget augue neque.

Aliquam vitae dolor tempor, bibendum lacus eget, posuere odio. Pellentesque lobortis, ipsum vitae volutpat commodo, magna massa pulvinar neque, at hendrerit enim elit sed nibh. Fusce interdum lorem vel libero egestas, ac dapibus mi dictum. Fusce quis purus purus. Nullam iaculis tristique lacus ut dictum. Vestibulum erat tortor, gravida id dolor ac, posuere varius libero. Integer quis quam aliquam, bibendum urna accumsan, ornare ipsum. Aenean pulvinar pulvinar nunc, ac consequat nulla. Suspendisse feugiat diam eget lorem condimentum faucibus. Integer vitae dolor diam. Nulla facilisi. Praesent rhoncus, risus a venenatis blandit, arcu lectus posuere nulla, suscipit porta ante nisl nec nibh. Suspendisse dapibus luctus accumsan.

Fusce eros diam, ultricies et tristique ac, egestas ut arcu. Nullam augue leo, auctor vel mollis in, feugiat vel elit. Morbi convallis tortor eget justo dapibus, ac vehicula ante tincidunt. Cras nec dolor neque. Proin facilisis arcu sed elit sollicitudin consequat. Nunc finibus elit quis elit porta viverra gravida non sem. Etiam sit amet nibh quis dolor tincidunt egestas et vel lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum scelerisque a leo et consequat. Ut sed ultricies diam. Nullam eget hendrerit diam. Proin et justo magna. Donec nisl ligula, tincidunt eu massa sit amet, vestibulum pretium ante.

Phasellus et scelerisque risus. Nunc mollis molestie neque eget vulputate. Mauris ac justo a lorem tempus tristique a at nunc. Ut finibus lectus non vestibulum tincidunt. Integer tellus nisl, lacinia in scelerisque vel, malesuada malesuada felis. Aliquam ultricies nisl id odio placerat suscipit. Donec mollis augue eget risus dignissim, eu euismod urna dapibus. Integer eget elementum urna. Duis finibus diam eget rhoncus pretium. Maecenas vehicula erat eu est finibus, non scelerisque tellus lacinia. Sed lorem est, rhoncus lacinia dictum non, venenatis quis nulla. Proin ac erat vitae ex gravida ultricies in et metus. Aliquam a tortor consectetur, fringilla ipsum sed, pharetra tortor. Praesent id rhoncus est, sit amet malesuada mauris.

Ut eget rhoncus turpis, pretium iaculis libero. Curabitur aliquet velit magna, sit amet ullamcorper nisl facilisis vitae. Praesent eget risus dolor. Cras aliquam urna sit amet quam rhoncus malesuada. Aliquam erat volutpat. Cras at eros et purus vulputate luctus. In hac habitasse platea dictumst. Morbi in facilisis quam. Donec malesuada in felis sit amet venenatis.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas aliquam velit id blandit luctus. Suspendisse dolor dolor, pretium id eros et, luctus porttitor lorem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer gravida, neque id commodo efficitur, nisi nisi dictum lectus, ut vehicula ex magna sit amet magna. Suspendisse purus urna, efficitur at rhoncus eget, dapibus eget nisl. Etiam tempus aliquam odio, ut scelerisque velit blandit sit amet. Phasellus sed viverra quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam sollicitudin tincidunt elit, suscipit molestie nibh facilisis id. Proin consectetur risus eu nunc commodo fringilla. Nam a dapibus nunc. Praesent cursus ornare lectus. Suspendisse eget diam ac leo aliquet pellentesque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis at faucibus risus.

Vestibulum nec justo eleifend, congue ante vel, feugiat est. Donec venenatis velit ac mattis feugiat. Duis tristique felis id ligula malesuada, a pharetra odio faucibus. Cras a mi luctus, feugiat arcu nec, laoreet nibh. Etiam ultrices ligula in odio bibendum convallis consequat at metus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam porta lacus ut luctus suscipit. In justo nisi, ultricies in sodales non, lacinia ut nisi. Sed maximus justo ligula, quis gravida velit maximus id. Quisque ex enim, volutpat id tortor vitae, aliquet sollicitudin odio. Etiam vehicula, nulla quis ultricies interdum, metus nisl ultrices metus, efficitur congue purus dui vitae nibh. Nullam interdum ultrices lorem, et suscipit eros pulvinar vel. Proin feugiat ligula ut neque semper, a venenatis ligula tempus. Duis est magna, bibendum sit amet porttitor id, aliquet eget dolor.

Mauris non mollis turpis. Maecenas neque lectus, mollis nec interdum a, posuere in leo. Morbi tempor sollicitudin orci vel interdum. Maecenas auctor erat libero, at posuere ligula vestibulum id. Cras vestibulum massa et felis rutrum consequat. Praesent laoreet, erat eget tempor commodo, sem nulla laoreet odio, sed auctor enim tellus vitae lorem. Vestibulum condimentum justo et dui consequat bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eu accumsan purus. Vivamus dignissim sed lorem sit amet imperdiet. Mauris sit amet lorem nisi. Donec id rutrum odio, at laoreet elit. Praesent eu sodales nunc. Duis a auctor nulla, vitae rhoncus dui. Morbi a lacus in augue sodales sodales a non eros.

Nam sed bibendum mauris, a venenatis neque. Sed posuere blandit lacus, sed feugiat ipsum fermentum id. Aenean nec velit tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas dictum feugiat mi, id facilisis justo pulvinar ut. Donec gravida quis leo id viverra. Cras sodales ex arcu, eu volutpat dui ultrices sed. Duis lectus leo, luctus quis tempor ut, egestas vel nisl. Pellentesque sodales, nunc id blandit finibus, libero mauris viverra sapien, nec sagittis neque libero in lacus. Phasellus ac ultrices diam. Aenean a mauris luctus ante venenatis finibus ut eu nunc. Proin pretium lobortis nibh quis vestibulum. Nulla pretium volutpat feugiat. In hac habitasse platea dictumst. Nullam nisi dolor, aliquet ac cursus id, sagittis porta erat. Aliquam vestibulum mi urna, et dignissim nisl mollis sit amet.

Morbi rhoncus maximus neque vel hendrerit. Vivamus vehicula enim nec lorem venenatis sagittis. Aenean vitae viverra ligula, eget ultrices odio. Proin egestas rutrum diam vitae faucibus. Fusce sagittis id neque sed gravida. Sed velit erat, blandit at lacinia a, aliquet ac diam. Ut in velit dolor. Donec consequat, nibh eu fermentum cursus, tortor risus fermentum neque, id tincidunt felis enim in nisi. Nulla nec diam ut tortor tempus ullamcorper. Maecenas nec risus rutrum, consectetur libero sit amet, mollis mi. Praesent pellentesque sapien vel orci egestas tristique. Donec in eros enim. Fusce porta at ligula vel pretium. Sed odio quam, eleifend a nibh sit amet, tristique rhoncus lorem. Aenean est ante, egestas non lorem in, fermentum iaculis neque.

Proin molestie lorem quis laoreet elementum. Ut quis orci sed erat maximus placerat. Proin gravida lobortis erat, aliquam vehicula nibh lacinia et. Sed eget est blandit, accumsan mauris at, dignissim ligula. Vestibulum et nisi justo. Suspendisse tincidunt, magna ut viverra scelerisque, metus dolor feugiat diam, nec feugiat neque turpis finibus neque. Fusce vehicula mauris id semper aliquam. Donec congue quis ligula id molestie. Curabitur gravida urna lectus, vel fermentum sem interdum tempus. Vestibulum vitae malesuada elit, et imperdiet orci. Suspendisse sit amet tristique lorem. Aliquam semper iaculis justo, at lacinia arcu bibendum id. Praesent sagittis bibendum mattis. Etiam sapien ante, vehicula eget ultrices eget, facilisis vel ante. Vivamus nunc dolor, rhoncus gravida diam eget, tincidunt faucibus nunc.

Proin id tellus molestie, auctor nulla eget, sodales enim. Vivamus dictum eu nunc eu pretium. Donec non consectetur velit. Duis quis risus eget orci efficitur euismod vitae et enim. Suspendisse potenti. Donec eget urna sollicitudin, vestibulum elit et, rhoncus enim. Pellentesque faucibus vitae tortor vel pellentesque. Integer posuere lacinia est non consequat.

In efficitur posuere erat. Fusce auctor orci ante. Suspendisse est dui, auctor maximus lacus id, gravida vestibulum metus. Vestibulum mi erat, luctus in varius non, ultricies in lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus sed est nibh. Praesent lacus dolor, commodo vel ornare ac, interdum vel ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin imperdiet arcu ante, et gravida felis lobortis eu. Integer accumsan lobortis neque eget mattis.

Morbi maximus ut diam sed facilisis. Curabitur a varius elit. Morbi dignissim scelerisque dui, ut finibus mi condimentum nec. Suspendisse pretium sagittis dolor sagittis fermentum. Cras sollicitudin felis at ante condimentum, at rhoncus massa vulputate. Donec ornare cursus euismod. Aliquam et diam nec dolor aliquet pellentesque nec sit amet turpis. Phasellus ut congue purus. Nullam placerat, lorem in rhoncus porttitor, mauris dolor luctus leo, sed egestas purus arcu eget ipsum. Praesent efficitur dui eget felis pulvinar, at ultrices nisi facilisis. Duis ac odio id est ornare laoreet sit amet eget diam.

In hac habitasse platea dictumst. Vestibulum ac felis justo. Nunc quis elit venenatis felis tincidunt fringilla id ac risus. Praesent nisl arcu, vehicula vel scelerisque vitae, pellentesque id erat. Nullam vestibulum, leo quis dapibus pretium, mi risus placerat magna, nec facilisis ante nunc vitae dolor. Praesent dignissim erat quam, et feugiat nulla pretium vitae. Praesent vitae sodales tortor.

Praesent commodo elit eget risus dignissim, vitae feugiat nunc finibus. Praesent ullamcorper mi et nibh varius, a dictum diam imperdiet. Nulla id libero ut ipsum hendrerit varius. Nam ullamcorper ex et nulla mattis tincidunt. Suspendisse eget lacus est. Curabitur rutrum, tellus in pretium mollis, ipsum justo finibus mi, vitae aliquet dui augue quis justo. Etiam tincidunt eu leo at condimentum. Donec venenatis pellentesque iaculis. Suspendisse a turpis a dolor accumsan aliquet. Aliquam erat volutpat. Nunc ac tempus turpis. Nam posuere mattis ultricies. Integer eget orci hendrerit, aliquet turpis at, rhoncus ipsum. Nulla eu euismod nisi, vitae sodales nibh. Pellentesque sed risus a justo bibendum bibendum. Sed placerat imperdiet libero, eu congue est placerat condimentum.

Donec vitae sapien arcu. Donec pretium magna ipsum, vitae rutrum enim facilisis venenatis. Sed eu orci vel velit placerat ultricies et at ante. Morbi dolor felis, molestie non efficitur sit amet, mollis eget ipsum. Donec condimentum tristique turpis a mollis. Donec turpis risus, ullamcorper id arcu quis, pretium efficitur orci. Phasellus molestie felis et commodo vulputate. Aliquam erat volutpat. Integer sagittis et ligula vel placerat. Mauris aliquam nisi in lobortis dapibus. Vestibulum ut aliquet lorem, a congue quam. Quisque gravida scelerisque libero, a elementum eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi sed eleifend ligula. Nulla facilisi.

Aenean urna arcu, dictum scelerisque est at, facilisis malesuada velit. Duis blandit mauris ac ipsum posuere, a pulvinar lacus tempus. Etiam congue elementum dui, non egestas lorem venenatis vitae. Vivamus bibendum, metus vitae sagittis tincidunt, lorem diam suscipit eros, eu congue elit dui at neque. Integer efficitur lobortis augue quis rutrum. Integer eleifend quis justo vitae pellentesque. Curabitur ut vulputate lorem.

Donec nec augue nec ligula semper facilisis. Mauris nec erat sit amet velit tempor rhoncus. Mauris sem odio, cursus id lacus non, fermentum pretium eros. Duis leo quam, commodo in tristique sit amet, dictum sit amet mauris. Sed lacinia id leo eu efficitur. Sed malesuada mollis faucibus. Ut suscipit lorem ac lacus hendrerit, et lobortis odio bibendum. Praesent libero felis, blandit et nisi at, consectetur accumsan nulla. Nulla feugiat elit risus, quis auctor felis aliquet vitae. Praesent elementum quam faucibus orci porta suscipit. Quisque tempor quis tellus at scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sem arcu, facilisis sit amet faucibus quis, euismod in metus. Vivamus fringilla turpis id vestibulum varius.

Suspendisse cursus nunc non posuere faucibus. Sed rhoncus lorem et ipsum congue rhoncus. Integer purus neque, iaculis in consectetur ac, condimentum id mauris. Duis sodales fermentum aliquam. Etiam sollicitudin diam magna, et interdum massa vestibulum convallis. Donec scelerisque metus sit amet dolor condimentum, ut scelerisque massa ultricies. Aliquam vehicula diam in odio rutrum aliquet. Nunc molestie leo sit amet sagittis tincidunt. Sed elementum blandit ligula nec hendrerit. Nulla laoreet arcu id odio condimentum egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris dignissim est id risus rutrum aliquet. In augue nisl, gravida eget neque ut, tristique maximus justo.

Vestibulum auctor ornare eros, ut vestibulum dui venenatis eget. Integer molestie a libero vel malesuada. Phasellus rhoncus nisi non vestibulum commodo. Suspendisse non dolor iaculis, aliquet dolor vel, maximus magna. Nulla pellentesque nibh eget nisi semper, quis faucibus mi elementum. Cras dignissim pellentesque sapien, et tincidunt nunc interdum in. Quisque nunc nulla, posuere sed mauris eu, dictum gravida lectus. Suspendisse ac augue nunc. Sed tempus libero at velit egestas ultricies. Phasellus consectetur turpis eros.

Proin tempor elit felis, tristique elementum justo lacinia ut. Duis blandit velit nec faucibus rutrum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam id nisl nunc. Proin in pretium nulla, ut convallis lacus. Nullam turpis nulla, aliquet non libero eget, sagittis pharetra risus. Nullam lacinia dignissim ante, at maximus purus consequat ac. Nulla sapien lorem, tempor vel finibus vitae, vehicula eget nunc. Maecenas finibus elementum turpis, et cursus neque porttitor eu. Praesent pulvinar aliquam erat, a iaculis est pretium quis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean aliquam orci accumsan, interdum ante et, euismod neque.

Ut mattis, quam at posuere aliquam, eros nibh cursus odio, sit amet tempor quam leo nec lacus. Curabitur bibendum libero vel tincidunt porttitor. Nam est turpis, sagittis nec neque in, ultrices dapibus nibh. Donec ac sollicitudin ante, a gravida leo. Praesent consequat, turpis at fringilla suscipit, ipsum lorem lacinia dui, a posuere elit dui nec neque. Vivamus at urna vel nibh pharetra tristique. Curabitur egestas nulla placerat, pellentesque ligula a, scelerisque orci. Quisque sed gravida leo. Nullam dictum quam id quam elementum varius. Vestibulum quis dui pharetra, finibus est tincidunt, aliquet ex. Curabitur dictum vel nulla sed aliquet. Suspendisse viverra dapibus lacus sed faucibus. Nunc volutpat metus quis est bibendum sodales. Phasellus ac augue enim.

Vivamus id tempor justo. Duis interdum sodales elit. Pellentesque iaculis volutpat ipsum ac laoreet. Morbi sed elit volutpat, vestibulum ipsum et, elementum erat. Maecenas tellus nisl, sagittis congue felis sit amet, mattis mollis lectus. Etiam tempor augue a enim congue, ac maximus felis accumsan. Nulla facilisi. Mauris rutrum feugiat urna, id blandit erat convallis ac.

Etiam eget felis nec nisl bibendum malesuada. Curabitur commodo, mauris ac sagittis sodales, ex libero pulvinar odio, varius ultrices metus sapien et augue. Morbi fermentum ex at eleifend bibendum. Curabitur nec enim eget tellus accumsan pretium. Nunc augue augue, suscipit a dapibus id, accumsan vel est. Suspendisse iaculis mi sit amet facilisis porta. Donec ut mollis risus, vel maximus metus. Fusce mollis turpis quam, ac posuere dolor ultrices sed. Sed consectetur purus sed dolor blandit sagittis. Duis quis egestas orci. Pellentesque id turpis faucibus, commodo elit et, dictum felis. Curabitur efficitur, metus at vulputate hendrerit, nibh risus porta neque, et tincidunt neque risus vitae mi. Donec a quam vitae sem finibus porta maximus quis ex.

`;
