defaults:
  run:
    working-directory: ./

name: CI on pull request

on: [pull_request]

jobs:
  prettier-eslint:
    name: prettier-eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    env:
      SKIP_ENV_VALIDATION: true
    steps:
      - uses: actions/checkout@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn install
      - name: Run Lint
        run: yarn lint
